version: '2.2'
services: 
  docker-mysql:
   container_name: mysql
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=osdashboard
     - MYSQL_PASSWORD=root
     - MYSQL_PORT=3306
   healthcheck:
       test: ["CMD", "/usr/local/bin/mysql-healthcheck.sh"]
       interval: 80s
       timeout: 10s
       retries: 20
   ports:
      - "3306:3306"
   expose:
      - "3306"
   volumes:
      - mysql-data:/var/lib/mysql
      - ./dumps/osdashboard.sql:/docker-entrypoint-initdb.d/osdashboard.sql
      - ./mysql-healthcheck.sh:/usr/local/bin/mysql-healthcheck.sh
   command: [
      "--log-bin=mysql-bin",
      "--server-id=1",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1",
      "--max-allowed-packet=16M"
      ]
   restart: always
   networks:
     backend:
       aliases: 
         - db
  
  cp-os-dashboard:
   container_name: cp-os-dashboard
   image: gcr.io/s4-oncsuite-dev-181912/cp-os-dashboard@sha256:3853c6fc4c60049d48b5b23e1c7f673e88f0fcecfba414a98147fb6984d9ef02
   depends_on:
     docker-mysql:
       condition: service_healthy
   ports:
     - 9090:9090
   restart: always
   env_file:
      - env/dashboard.env
   networks:
     backend:
       aliases: 
         - dashboard

  cp-os-report:
   container_name: cp-os-report
   image: gcr.io/s4-oncsuite-dev-181912/cp-os-report@sha256:ea4b193a6ce8cd104a4c89ad92948ed5cb1df29b261fb4d193e65dbedb26b0c1
   depends_on:
     docker-mysql:
       condition: service_healthy
   ports:
     - 9095:9095
   restart: always
   env_file:
     - env/report.env
   networks:
     backend:
       aliases: 
         - report            
    
networks:
  backend:

volumes:
  mysql-data:
