version: '2.2'
services: 
  docker-mysql:
   container_name: mysql
   image: mysql:5.7.20
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=osdashboard
     - MYSQL_PASSWORD=root
     - MYSQL_PORT=3306
   healthcheck:
       test: ["CMD", "/usr/local/bin/mysql-healthcheck.sh"]
       interval: 60s
       timeout: 10s
       retries: 10
   ports:
      - "3306:3306"
   expose:
      - "3306"
   volumes:
      - mysql-data:/var/lib/mysql
      - ./dumps/osdashboard.sql:/docker-entrypoint-initdb.d/osdashboard.sql
      - ./mysql-healthcheck.sh:/usr/local/bin/mysql-healthcheck.sh
   command: [
      "--log-bin=mysql-bin",
      "--server-id=1",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1"
      ]
   restart: always
   network_mode: bridge
  
  cp-os-dashboard:
    image: gcr.io/s4-oncsuite-dev-181912/cp-os-dashboard@sha256:76082d0427b043325513ab31a6b5ef58dc2f372d1bb1e246cbcb444d446f1931
    depends_on:
      docker-mysql:
        condition: service_healthy
    links:
      - docker-mysql
    ports:
      - 9090:9090
    restart: always
    env_file:
      - env/dashboard.env
    network_mode: bridge

volumes:
  mysql-data:
