version: '2.2'
services: 
  cp-os-dashboard:
    container_name: cp-os-dashboard
    image: gcr.io/s4-oncsuite-dev-181912/cp-os-dashboard@sha256:3853c6fc4c60049d48b5b23e1c7f673e88f0fcecfba414a98147fb6984d9ef02
    ports:
      - 9090:9090
    restart: always
    env_file:
      - env/dashboard-dev.env
    networks:
        docker_net:
            ipv4_address: 172.28.1.2

  cp-os-report:
    container_name: cp-os-report
    image: gcr.io/s4-oncsuite-dev-181912/cp-os-report@sha256:ea4b193a6ce8cd104a4c89ad92948ed5cb1df29b261fb4d193e65dbedb26b0c1
    ports:
      - 9095:9095
    restart: always
    env_file:
      - env/report-dev.env
    networks:
        docker_net:
            ipv4_address: 172.28.1.3            
    
networks:
    docker_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

volumes:
  mysql-data:
