version: '2.2'

services: 
  dnsdock:
   image: tonistiigi/dnsdock
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - 172.17.0.1:53:53/udp
  
  docker-mysql:
   container_name: mysql
   image: mysql:5.7
   dns: 172.17.0.1
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=osdashboard
     - MYSQL_PASSWORD=root
     - MYSQL_PORT=3306
     - DNSDOCK_NAME=oncsuite
     - DNSDOCK_IMAGE=db
   healthcheck:
       test: ["CMD", "/usr/local/bin/mysql-healthcheck.sh"]
       interval: 80s
       timeout: 10s
       retries: 20
   ports:
      - "3306:3306"
   expose:
      - "3306"
   volumes:
      - mysql-data:/var/lib/mysql
      - ./dumps/osdashboard.sql:/docker-entrypoint-initdb.d/osdashboard.sql
      - ./mysql-healthcheck.sh:/usr/local/bin/mysql-healthcheck.sh
   command: [
      "--log-bin=mysql-bin",
      "--server-id=1",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1",
      "--max-allowed-packet=16M"
      ]
   restart: always
  
  cp-os-dashboard:
    container_name: cp-os-dashboard
    image: gcr.io/s4-oncsuite-dev-181912/cp-os-dashboard@sha256:3853c6fc4c60049d48b5b23e1c7f673e88f0fcecfba414a98147fb6984d9ef02
    dns: 172.17.0.1
    depends_on:
      docker-mysql:
        condition: service_healthy
    ports:
      - 9090:9090
    restart: always
    env_file:
      - env/dashboard.env

  cp-os-report:
    container_name: cp-os-report
    image: gcr.io/s4-oncsuite-dev-181912/cp-os-report@sha256:c286e71bac7dd1e5ea083db83b96659832c1d1a8fbc5589a205c292baba3a69f
    dns: 172.17.0.1
    depends_on:
      docker-mysql:
        condition: service_healthy
    ports:
      - 9095:9095
    restart: always
    env_file:
      - env/report.env
    
volumes:
  mysql-data:
